spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: p@ssw0rd
  jpa:
    show-sql: true
    properties:
      hibernate:
      format_sql: true

server:
  error:
    include-stacktrace: never
